import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Upload from '../components/upload'
import Preview from '../components/preview'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Quote me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Quote Me</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          upload picture
        </p>
        <Upload></Upload>
        <Preview></Preview>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/mjkodkks"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            DKKs
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
