import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Upload from '../components/upload'
import Preview from '../components/preview'
import { useRef, useState } from 'react'
import { toPng, toJpeg, toBlob, toPixelData, toSvg } from 'html-to-image';

const Home: NextPage = () => {
  const [img, setImg] = useState()
  const ref = useRef(null);

  function onImgChange(e) {
    // console.log(e)
    setImg(e)
  }

  function onSave(e) {
    console.log(ref)
    if (ref.current) {
      toPng(ref.current)
        .then(function (dataUrl) {
          // var img = document.createElement('img')
          // img.src = dataUrl;
          var aDownloadLink = document.createElement('a');
          // Add the name of the file to the link
          aDownloadLink.download = 'my_quote.png';
          // Attach the data to the link
          aDownloadLink.href = dataUrl;
          // Get the code to click the download link
          aDownloadLink.click();
        })
        .catch(function (error) {
          console.error('oops, something went wrong!', error);
        });
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Quote me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Quote Me</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          upload picture
        </p>
        <Upload onImgChange={onImgChange}></Upload>
        <Preview imageSrc={img} ref={ref}></Preview>
        <button onClick={onSave}>Save</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/mjkodkks"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            DKKs
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
